import { Router } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { z } from 'zod';
import { prisma } from '../../config/database';
import { authenticate, authorize } from '../../middleware/auth.middleware';
import { pagination, parseDate, schoolScope } from '../../utils/route-helpers';
import { NotFoundError, ValidationError } from '../../utils/errors';

export const feeRoutes = Router();
feeRoutes.use(authenticate);
const feeInput = z.object({ studentId: z.string().uuid(), feeType: z.string().min(1).max(100), amount: z.number().positive(), dueDate: z.string().optional(), termId: z.string().uuid().optional(), academicYearId: z.string().uuid().optional() });
const paymentInput = z.object({ studentId: z.string().uuid(), feeRecordId: z.string().uuid().optional(), amount: z.number().positive(), paymentMethod: z.string().max(50).optional(), transactionRef: z.string().max(255).optional(), receiptNumber: z.string().max(100).optional(), notes: z.string().max(2000).optional() });

feeRoutes.get('/', authorize('super_admin', 'school_admin', 'teacher', 'parent', 'student'), async (req, res, next) => { try { const schoolId = schoolScope(req); const { page, pageSize, skip, take } = pagination(req); const where = { schoolId, ...(req.user!.role === 'student' ? { student: { userId: req.user!.userId } } : {}), ...(typeof req.query.studentId === 'string' ? { studentId: req.query.studentId } : {}) }; const [data, total] = await prisma.$transaction([prisma.feeRecord.findMany({ where, skip, take, orderBy: { createdAt: 'desc' }, include: { student: { select: { id: true, studentId: true, firstName: true, lastName: true } }, payments: true } }), prisma.feeRecord.count({ where })]); res.json({ success: true, data, meta: { page, pageSize, total } }); } catch (error) { next(error); } });
feeRoutes.post('/', authorize('super_admin', 'school_admin'), async (req, res, next) => { try { const input = feeInput.parse(req.body); const schoolId = schoolScope(req); if (!(await prisma.student.findFirst({ where: { id: input.studentId, schoolId } }))) throw new ValidationError('Student is outside your school'); const data = await prisma.feeRecord.create({ data: { id: uuidv4(), schoolId, studentId: input.studentId, feeType: input.feeType, amount: input.amount, dueDate: parseDate(input.dueDate, 'dueDate'), termId: input.termId, academicYearId: input.academicYearId } }); res.status(201).json({ success: true, data }); } catch (error) { next(error); } });
feeRoutes.get('/student/:id', authorize('super_admin', 'school_admin', 'teacher', 'parent', 'student'), async (req, res, next) => { try { const schoolId = schoolScope(req); const student = await prisma.student.findFirst({ where: { id: req.params.id, schoolId, ...(req.user!.role === 'student' ? { userId: req.user!.userId } : {}) } }); if (!student) throw new NotFoundError('Student not found'); const data = await prisma.feeRecord.findMany({ where: { studentId: student.id, schoolId }, include: { payments: true }, orderBy: { createdAt: 'desc' } }); res.json({ success: true, data }); } catch (error) { next(error); } });
feeRoutes.post('/payment', authorize('super_admin', 'school_admin'), async (req, res, next) => { try { const input = paymentInput.parse(req.body); const schoolId = schoolScope(req); const student = await prisma.student.findFirst({ where: { id: input.studentId, schoolId } }); if (!student) throw new ValidationError('Student is outside your school'); const fee = input.feeRecordId ? await prisma.feeRecord.findFirst({ where: { id: input.feeRecordId, studentId: input.studentId, schoolId } }) : null; if (input.feeRecordId && !fee) throw new NotFoundError('Fee record not found'); if (fee && input.amount > Number(fee.amount) - Number(fee.amountPaid)) throw new ValidationError('Payment exceeds outstanding balance'); const payment = await prisma.$transaction(async (tx) => { const created = await tx.payment.create({ data: { id: uuidv4(), schoolId, studentId: input.studentId, feeRecordId: input.feeRecordId, amount: input.amount, paymentMethod: input.paymentMethod, transactionRef: input.transactionRef, receiptNumber: input.receiptNumber, receivedBy: req.user!.userId, notes: input.notes } }); if (fee) { const amountPaid = Number(fee.amountPaid) + input.amount; await tx.feeRecord.update({ where: { id: fee.id }, data: { amountPaid, status: amountPaid >= Number(fee.amount) ? 'paid' : 'partial' } }); } return created; }); res.status(201).json({ success: true, data: payment }); } catch (error) { next(error); } });
